"""Tests for engine/image_io.py against the synthetic-photo proxies in
synthetic_photos/ (generated by generate_synthetic_photos.py from real,
already-validated Kaggle CSV patterns -- see that module's docstring for
why synthetic photos, not real ones, are used for ground-truth testing).

These tests are skipped if the synthetic photo set hasn't been generated
(keeps the main suite runnable without the image_io dependencies/fixtures
present), rather than failing.
"""

from __future__ import annotations

import json
import os

import cv2
import numpy as np
import pytest
from scipy.spatial import cKDTree

from engine import image_io

SYNTHETIC_DIR = os.path.join(os.path.dirname(__file__), "..", "synthetic_photos")
MATCH_TOLERANCE_PX = 6.0

pytestmark = pytest.mark.skipif(
    not os.path.isdir(SYNTHETIC_DIR) or not os.listdir(SYNTHETIC_DIR),
    reason="synthetic_photos/ not generated -- run generate_synthetic_photos.py first",
)


def _load_ground_truth(stem: str) -> dict:
    with open(os.path.join(SYNTHETIC_DIR, f"{stem}.json")) as f:
        return json.load(f)


def _image_path(stem: str) -> str:
    return os.path.join(SYNTHETIC_DIR, f"{stem}.jpg")


def _deskewed_gt_pixels(stem: str, preprocessed: image_io.Preprocessed) -> np.ndarray:
    """Ground-truth dot pixel positions, rotated into the SAME deskewed
    frame preprocess() produced (see validate_image_io.py for why this
    is necessary: comparing raw pixel positions across the pre- and
    post-deskew frames is an apples-to-oranges coordinate mismatch)."""
    gt = _load_ground_truth(stem)
    gt_px = np.array(list(gt["dot_pixel_positions"].values()), dtype=np.float32)
    img = cv2.imread(_image_path(stem))
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w / 2, h / 2), preprocessed.rotation_deg, 1.0)
    return cv2.transform(gt_px.reshape(-1, 1, 2), M).reshape(-1, 2)


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_detect_lattice_dot_count_matches_ground_truth(stem):
    gt = _load_ground_truth(stem)
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)

    # allow a small tolerance for spurious/missed detections rather than
    # demanding an exact count match
    assert abs(len(lattice.lattice_coords) - gt["n_nodes"]) <= max(2, round(0.03 * gt["n_nodes"]))


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_detect_lattice_positions_match_ground_truth_within_tolerance(stem):
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)
    gt_px = _deskewed_gt_pixels(stem, preprocessed)
    det_px = np.array(lattice.pixel_positions)

    tree = cKDTree(det_px)
    d, _ = tree.query(gt_px)
    matched_fraction = (d < MATCH_TOLERANCE_PX).mean()
    assert matched_fraction > 0.95


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_trace_path_edge_set_matches_ground_truth_within_tolerance(stem):
    """Edges are compared as DISTINCT connectivity (not exact strand
    multiplicity -- see engine.motifs.compression_ratio's docstring for
    why that's the primary currency used elsewhere in this project too),
    after remapping recovered lattice coordinates onto ground-truth node
    labels via nearest detected-dot-to-ground-truth-dot pixel matching."""
    gt = _load_ground_truth(stem)
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)
    recovered_edges = image_io.trace_path(preprocessed, lattice)

    gt_px = _deskewed_gt_pixels(stem, preprocessed)
    gt_labels = list(gt["dot_pixel_positions"].keys())
    det_px = np.array(lattice.pixel_positions)

    tree_gt = cKDTree(gt_px)
    d, idx = tree_gt.query(det_px)
    recovered_to_gt = {}
    for i, (dist, j) in enumerate(zip(d, idx)):
        if dist < MATCH_TOLERANCE_PX:
            node = tuple(int(v) for v in gt_labels[j].split(","))
            recovered_to_gt[lattice.lattice_coords[i]] = node

    recovered_distinct = {
        frozenset({recovered_to_gt[a], recovered_to_gt[b]})
        for a, b in recovered_edges
        if a in recovered_to_gt and b in recovered_to_gt
    }
    gt_distinct = {frozenset({tuple(a), tuple(b)}) for a, b in gt["edges"]}

    recall = len(recovered_distinct & gt_distinct) / len(gt_distinct)
    precision = len(recovered_distinct & gt_distinct) / len(recovered_distinct)
    assert recall > 0.95
    assert precision > 0.95


def test_build_graph_produces_engine_compatible_multigraph():
    """The single public entry point should hand back exactly the format
    engine/graph_io.py produces: an nx.MultiGraph with (int, int) nodes,
    consumable by motifs/symmetry/generation/validity with zero changes."""
    import networkx as nx

    from engine import motifs, validity

    G = image_io.build_graph(_image_path("kolam19_k1"))
    assert isinstance(G, nx.MultiGraph)
    assert G.number_of_nodes() > 0
    assert all(
        isinstance(n, tuple) and len(n) == 2 and all(isinstance(v, int) for v in n) for n in G.nodes()
    )

    # zero-change downstream compatibility: these calls must not raise
    result = validity.check_validity(G)
    assert "is_eulerian_circuit" in result

    dots = set(G.nodes())
    interior = motifs.interior_points(dots, radius=1)
    placements, residual, _fully_covered = motifs.induce_motif_set_adaptive(
        G, interior, dots, max_radius=2, max_motifs_per_radius=50
    )
    assert isinstance(placements, list)
